sudo: required
dist: trusty
install:
  - sudo apt-get update
  - sudo apt-get install -y python3-pyqt5.qtwebkit python3-pip
  - sudo /usr/bin/pip3 install Markups Markdown docutils
script:
  - xvfb-run -a -s "-screen 0 1024x768x24" /usr/bin/python3 setup.py test
