environment:

  matrix:
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"

install:
  - "%PYTHON%\\python.exe -m pip install PyQt5 Markdown docutils Markups"

build: off

test_script:
  - "%PYTHON%\\python.exe setup.py test"
